apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  DB_PASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.auth.postgresPassword | b64enc }}{{ else }}{{ .Values.externalDatabase.password | b64enc }}{{ end }}

